# Generated by Django 5.2 on 2025-04-05 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PowerSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('reason', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('vibration_level', models.FloatField()),
                ('motor_voltage', models.FloatField()),
                ('motor_current', models.FloatField()),
                ('power_consumption', models.FloatField()),
                ('bottle_mass', models.FloatField()),
                ('bottle_brightness', models.FloatField()),
                ('good_product', models.IntegerField()),
                ('bad_product', models.IntegerField()),
                ('power_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor.powersystem')),
            ],
        ),
    ]
